### PR TITLE
German license plate validation

### PR DESCRIPTION
**Pull request by WickedSilver**
This PR adds german license plate validation.

# TODOs
* ~Find more reference material on how to format the license plates~
* ~Add formatting for more side codes~
* ~Find out options to the false positives of district formatting. [AAB1337 could be district A as well as AA](https://regex101.com/r/PvG5GS/3).~ formatting is now based on the input string (with spaces and dashes if entered), if the input string is without spaces or dashes it uses the district with the least amount of characters - which should be the largest and therefore has the highest chance to be right.
* ~Finish validation test~
* ~Create formatting test~

### CODE REVIEW

**Comment by Intrepidity** [comment]
Hey @WickedSilver, thanks for your contribution! Looks good on first sight. As you probably noticed this library is a bit unmaintained, which is why Travis is failing on the PHP 5.3 build ;) I'll invest some time soon in getting the travis checks up and running, migrating to PHP 7.x and to go through your PR :) Fun to see someone is actually still using this.

**Comment by Intrepidity** [comment]
I changed the travis config to check 5.6/7.0/7.1 :) If you rebase on top of master your build should pass now.

**Comment by Intrepidity** [comment]
Would you like me to merge it or do you want to continue working on your todo's first?

**Comment by WickedSilver** [comment]
Thanks for the fast response and for the great foundation of the library 😃 
We are using the bundle for a month now and might start using it in our other software.
I will work on some of the TODO's first. Are you still using this library by the way?

**Comment by Intrepidity** [comment]
Me personally no, I used it when working for a previous employer, perhaps they're still using it, I don't know :)

**Comment by WickedSilver** [comment]
Thought so :)
I updated the TODO's of the PR message.
You can merge the PR if you are happy with the changes.

**Comment by Intrepidity** [comment]
Looks good, merged and thanks! :)

**Comment by WickedSilver** [comment]
Awesome! Thanks and no problem :)

**Pull request merged**
